# ---- Build stage ----
FROM node:24-alpine AS builder

# 1. Declare all build arguments (matching your .env keys)
ARG GOOGLE_MAPS_API_KEY
ARG CESIUM_ION_TOKEN
ARG OPENAI_API_KEY
ARG OPENAI_REALTIME_MODEL
ARG OPENAI_REALTIME_MODEL_MINI
ARG OPENAI_REALTIME_VOICE
ARG OPENAI_REALTIME_REASONING_EFFORT
ARG OPENAI_REALTIME_CONTEXT_TOKENS
ARG OPENAI_REALTIME_CONTEXT_RETENTION
ARG OPENAI_HUD_SUMMARY_MODEL
ARG OPENSKY_AUTH_MODE
ARG OPENSKY_CLIENT_ID
ARG OPENSKY_CLIENT_SECRET
ARG PORT
ARG VITE_AIS_LIVE_API_URL
ARG VITE_AIS_LIVE_MAX_ROWS
ARG VITE_AIS_LIVE_LABEL_MAX_ROWS
ARG AISSTREAM_API_KEY
ARG TOMTOM_API_KEY
ARG FIRMS_MAP_KEY

WORKDIR /app

# Copy package files and install
COPY package*.json ./
RUN npm ci

# Copy source
COPY . .

# 2. Set them as environment variables for the build process
ENV GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY
ENV CESIUM_ION_TOKEN=$CESIUM_ION_TOKEN
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV OPENAI_REALTIME_MODEL=$OPENAI_REALTIME_MODEL
ENV OPENAI_REALTIME_MODEL_MINI=$OPENAI_REALTIME_MODEL_MINI
ENV OPENAI_REALTIME_VOICE=$OPENAI_REALTIME_VOICE
ENV OPENAI_REALTIME_REASONING_EFFORT=$OPENAI_REALTIME_REASONING_EFFORT
ENV OPENAI_REALTIME_CONTEXT_TOKENS=$OPENAI_REALTIME_CONTEXT_TOKENS
ENV OPENAI_REALTIME_CONTEXT_RETENTION=$OPENAI_REALTIME_CONTEXT_RETENTION
ENV OPENAI_HUD_SUMMARY_MODEL=$OPENAI_HUD_SUMMARY_MODEL
ENV OPENSKY_AUTH_MODE=$OPENSKY_AUTH_MODE
ENV OPENSKY_CLIENT_ID=$OPENSKY_CLIENT_ID
ENV OPENSKY_CLIENT_SECRET=$OPENSKY_CLIENT_SECRET
ENV PORT=$PORT
ENV VITE_AIS_LIVE_API_URL=$VITE_AIS_LIVE_API_URL
ENV VITE_AIS_LIVE_MAX_ROWS=$VITE_AIS_LIVE_MAX_ROWS
ENV VITE_AIS_LIVE_LABEL_MAX_ROWS=$VITE_AIS_LIVE_LABEL_MAX_ROWS
ENV AISSTREAM_API_KEY=$AISSTREAM_API_KEY
ENV TOMTOM_API_KEY=$TOMTOM_API_KEY
ENV FIRMS_MAP_KEY=$FIRMS_MAP_KEY

# 3. Build the app (this inlines all env vars)
RUN npm run build

# ---- Production stage ----
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# Configure nginx for client-side routing
RUN echo 'server { \
    listen 80; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html; \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
